# Generated by Django 4.1.7 on 2023-02-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='auditor',
            field=models.CharField(choices=[('1', 'Bassotti'), ('2', 'Pezzuca'), ('3', 'Cataldo'), ('4', "D'Onofrio"), ('5', 'Grandolfo'), ('6', 'Aiello')], default='Bassotti', max_length=300),
        ),
    ]
