# Generated by Django 4.1.7 on 2023-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='auditor',
            name='nome_auditor',
            field=models.CharField(choices=[('1', 'Bassotti'), ('2', 'Pezzuca'), ('3', 'Cataldo'), ('4', "D'Onofrio"), ('5', 'Grandolfo'), ('6', 'Aiello')], default='Bassotti', max_length=300),
        ),
    ]
