# Generated by Django 4.1.7 on 2023-02-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schemacerificativo_delete_book_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemaCerificativo',
            new_name='SchemaCertificativo',
        ),
        migrations.AddField(
            model_name='auditor',
            name='schema_auditing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.schemacertificativo'),
            preserve_default=False,
        ),
    ]
