# Generated by Django 4.1.7 on 2023-02-27 17:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_schemacerificativo_schemacertificativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaTeamCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ref_cliente', models.CharField(choices=[('1', 'dott. Fabio Fivoli'), ('2', 'ing. Marco Bongiorni'), ('3', 'Miria Felici'), ('4', 'Daniela Paci'), ('5', 'Paolo Cacchione'), ('6', 'Luigi Roma'), ('7', 'Michele Manella')], default='Marco Bongiorni', max_length=300)),
                ('email_ref_cliente', models.EmailField(max_length=254)),
                ('cellulare_ref_cliente', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ruolo_ref_cliente', models.CharField(choices=[('1', 'RSPP'), ('2', 'ASPP')], default='ASPP', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
