# Generated by Django 4.1.7 on 2023-03-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_anagraficateamcliente_delete_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnagraficaTeamCliente',
        ),
    ]
