# Generated by Django 4.1.7 on 2023-03-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_anagraficateamcliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor',
            options={'verbose_name': 'Auditor', 'verbose_name_plural': 'Auditor'},
        ),
        migrations.AlterModelOptions(
            name='schemacertificativo',
            options={'verbose_name_plural': 'Schema Certificativo'},
        ),
        migrations.AlterField(
            model_name='auditor',
            name='nome_auditor',
            field=models.CharField(default='Bassotti', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='schema_auditing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Scelta_Schema', to='app.schemacertificativo'),
        ),
        migrations.AlterField(
            model_name='schemacertificativo',
            name='schema_certificazione',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
