# Generated by Django 4.1.7 on 2023-03-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_auditor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='schema_auditing',
        ),
        migrations.AddField(
            model_name='schemacertificativo',
            name='auditor_schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.auditor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditor',
            name='nome_auditor',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
