# Generated by Django 4.1.7 on 2023-03-02 09:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_schemacertificativo_auditor_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaSitiCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sito_nome', models.CharField(max_length=300)),
                ('indirizzo_sito', models.TextField()),
            ],
            options={
                'verbose_name': 'Sito Cliente',
                'verbose_name_plural': 'Sito del Cliente',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaTeamCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ref_cliente', models.CharField(max_length=300, unique=True)),
                ('cellulare_ref_cliente', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ruolo_ref_cliente', models.CharField(max_length=300, unique=True)),
                ('acronimo_ref_sito', models.CharField(max_length=300, unique=True)),
                ('note_ref_sito', models.CharField(max_length=300, unique=True)),
                ('schema_certificativo', models.ManyToManyField(to='app.anagraficasiticliente')),
            ],
            options={
                'verbose_name': 'Anagrafica Cliente',
                'verbose_name_plural': 'Anagrafica del Cliente',
            },
        ),
    ]
