# Generated by Django 4.1.7 on 2023-03-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_anagraficasiticliente_anagraficateamcliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anagraficateamcliente',
            old_name='schema_certificativo',
            new_name='sito_cliente',
        ),
    ]
