# Generated by Django 4.1.7 on 2023-03-02 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_schema_certificativo_anagraficateamcliente_sito_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficasiticliente',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
