# Generated by Django 4.1.7 on 2023-03-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_anagraficasiticliente_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficasiticliente',
            name='location',
        ),
    ]
