# Generated by Django 4.1.7 on 2023-03-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_anagraficasiticliente_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficateamcliente',
            name='sito_cliente',
        ),
        migrations.DeleteModel(
            name='AnagraficaSitiCliente',
        ),
        migrations.DeleteModel(
            name='AnagraficaTeamCliente',
        ),
    ]
