# Generated by Django 4.1.7 on 2023-03-04 18:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_anagraficateamcliente_sito_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaTeamCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ref_cliente', models.CharField(max_length=300)),
                ('email_ref_cliente', models.EmailField(max_length=254)),
                ('cellulare_ref_cliente', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ruolo_ref_cliente', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Anagrafica Cliente',
                'verbose_name_plural': 'Anagrafica Cliente',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaSitiCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo_sito', models.CharField(max_length=300)),
                ('team_cliente', models.ManyToManyField(to='app.anagraficateamcliente')),
            ],
            options={
                'verbose_name': 'Anagrafica Cliente',
                'verbose_name_plural': 'Anagrafica Cliente',
            },
        ),
    ]
