# Generated by Django 4.1.7 on 2023-03-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_anagraficateamcliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficasiticliente',
            name='location',
        ),
    ]
