# Generated by Django 4.1.7 on 2023-03-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
