# Generated by Django 4.1.7 on 2023-03-20 13:47

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='anagraficasiticliente',
            name='ubicazione',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
