# Generated by Django 4.1.7 on 2023-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_nazionientifinanziari'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficasiticliente',
            name='anno_audit',
            field=models.CharField(choices=[('1', '2023'), ('2', '2023'), ('3', '2023'), ('4', '2022'), ('5', '2022'), ('6', '2022')], default='1', max_length=20),
        ),
    ]
