# Generated by Django 4.1.7 on 2023-03-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_anagraficasiticliente_anno_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
