# Generated by Django 4.1.7 on 2023-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_anagraficasiticliente_anno_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='foto',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
