# Generated by Django 4.1.7 on 2023-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_auditor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='foto',
            field=models.FileField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
